/*
 * This file was automatically generated by SmartUnit
 */

package smartunit.com.lastcalc;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import com.lastcalc.TokenList;
import com.lastcalc.Tokenizer;
import org.junit.runner.RunWith;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class Tokenizer_SSTest extends Tokenizer_SSTest_scaffolding {
// allCoveredLines:[32, 61, 63, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 80, 81, 83, 84, 85, 87, 90, 92, 100, 101, 102, 106, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131]

  @Test(timeout = 4000)
  public void test_equals_00()  throws Throwable  {
      //caseID:447cce6497762a897e0cb29a1fa23693
      //CoveredLines: [32, 100, 101, 102, 119, 120]
      //Input_0_Object: \"com.google.common.base.Preconditions\"
      //Assert: assertTrue(method_result);
      
      Tokenizer.QuotedString tokenizer_QuotedString0 = new Tokenizer.QuotedString("com.google.common.base.Preconditions");
      Tokenizer tokenizer0 = new Tokenizer();
      
      //Call method: equals
      boolean boolean0 = tokenizer_QuotedString0.equals(tokenizer_QuotedString0);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_01()  throws Throwable  {
      //caseID:90733e1c7547b32c3df508c0d129ec32
      //CoveredLines: [32, 100, 101, 102, 119, 121, 122]
      //Input_0_Object: null
      //Assert: assertFalse(method_result);
      
      Tokenizer.QuotedString tokenizer_QuotedString0 = new Tokenizer.QuotedString("H%cY(2");
      Tokenizer tokenizer0 = new Tokenizer();
      
      //Call method: equals
      boolean boolean0 = tokenizer_QuotedString0.equals(null);
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_02()  throws Throwable  {
      //caseID:a62a9dd9a1b483939a5f77bdb0f23971
      //CoveredLines: [100, 101, 102, 119, 121, 123, 124]
      //Input_0_Object: com.lastcalc.Tokenizer
      //Assert: assertFalse(method_result);
      
      Tokenizer.QuotedString tokenizer_QuotedString0 = new Tokenizer.QuotedString("com.lastcalc.Tokenizer");
      
      //Call method: equals
      boolean boolean0 = tokenizer_QuotedString0.equals("com.lastcalc.Tokenizer");
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_03()  throws Throwable  {
      //caseID:c5f87f38fba1afa3673654a5a995cb75
      //CoveredLines: [32, 100, 101, 102, 119, 121, 123, 125, 126, 129, 131]
      //Input_0_Object: \"\\\"\"
      //Assert: assertTrue(method_result);
      
      Tokenizer.QuotedString tokenizer_QuotedString0 = new Tokenizer.QuotedString("\"");
      Tokenizer.QuotedString tokenizer_QuotedString1 = new Tokenizer.QuotedString("\"");
      Tokenizer tokenizer0 = new Tokenizer();
      
      //Call method: equals
      boolean boolean0 = tokenizer_QuotedString0.equals(tokenizer_QuotedString1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_04()  throws Throwable  {
      //caseID:f371d3b9090cec408d2318bb86de0c61
      //CoveredLines: [32, 100, 101, 102, 119, 121, 123, 125, 126, 127, 131]
      //Input_0_Object: (String) null
      //Assert: assertTrue(method_result);
      
      Tokenizer.QuotedString tokenizer_QuotedString0 = new Tokenizer.QuotedString((String) null);
      Tokenizer.QuotedString tokenizer_QuotedString1 = new Tokenizer.QuotedString((String) null);
      Tokenizer tokenizer0 = new Tokenizer();
      
      //Call method: equals
      boolean boolean0 = tokenizer_QuotedString0.equals(tokenizer_QuotedString1);
      
      //Test Result Assert
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_05()  throws Throwable  {
      //caseID:3b2912e1351c1777d3b887cb019ded1f
      //CoveredLines: [32, 100, 101, 102, 119, 121, 123, 125, 126, 127, 128]
      //Input_0_Object: \"3\"
      //Assert: assertFalse(method_result);
      
      Tokenizer.QuotedString tokenizer_QuotedString0 = new Tokenizer.QuotedString((String) null);
      Tokenizer.QuotedString tokenizer_QuotedString1 = new Tokenizer.QuotedString("3");
      
      //Test Result Assert
      assertFalse(tokenizer_QuotedString1.equals((Object)tokenizer_QuotedString0));
      
      Tokenizer tokenizer0 = new Tokenizer();
      
      //Call method: equals
      boolean boolean0 = tokenizer_QuotedString0.equals(tokenizer_QuotedString1);
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test_equals_06()  throws Throwable  {
      //caseID:b3a41288e7805a413eff9e6f943889e2
      //CoveredLines: [32, 100, 101, 102, 119, 121, 123, 125, 126, 129, 130]
      //Input_0_Object: \"equalitySymbols\"
      //Assert: assertFalse(method_result);
      
      Tokenizer.QuotedString tokenizer_QuotedString0 = new Tokenizer.QuotedString("\"");
      Tokenizer.QuotedString tokenizer_QuotedString1 = new Tokenizer.QuotedString("equalitySymbols");
      Tokenizer tokenizer0 = new Tokenizer();
      
      //Call method: equals
      boolean boolean0 = tokenizer_QuotedString0.equals(tokenizer_QuotedString1);
      
      //Test Result Assert
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test_toString_07()  throws Throwable  {
      //caseID:7e81dedf71ecd58cf2204fc9905b5fda
      //CoveredLines: [100, 101, 102, 106]
      //Assert: assertEquals("\"50\"", method_result);
      
      Tokenizer.QuotedString tokenizer_QuotedString0 = new Tokenizer.QuotedString("50");
      
      //Call method: toString
      String string0 = tokenizer_QuotedString0.toString();
      
      //Test Result Assert
      assertEquals("\"50\"", string0);
  }

  @Test(timeout = 4000)
  public void test_tokenize_08()  throws Throwable  {
      //caseID:1fee7ddcbeae6a033854bc2e952ede28
      //CoveredLines: [61, 63, 65, 66, 67, 76, 77, 83, 84, 87, 90]
      //Input_0_String: p%2aF
      //Assert: assertEquals(4, method_result.size());
      
      
      //Call method: tokenize
      TokenList tokenList0 = Tokenizer.tokenize("p%2aF");
      
      //Test Result Assert
      assertEquals(4, tokenList0.size());
  }

  @Test(timeout = 4000)
  public void test_tokenize_09()  throws Throwable  {
      //caseID:34ab10b52cfd531d788a49e4e0c66ed2
      //CoveredLines: [61, 63, 65, 66, 67, 77, 83, 84, 85, 87, 90, 92]
      //Input_0_String: mo#iLmb#0b1f]F/L
      //Assert: assertEquals(10, method_result.size());
      
      
      //Call method: tokenize
      TokenList tokenList0 = Tokenizer.tokenize("mo#iLmb#0b1f]F/L");
      
      //Test Result Assert
      assertEquals(10, tokenList0.size());
  }

  @Test(timeout = 4000)
  public void test_tokenize_10()  throws Throwable  {
      //caseID:541b5c26c00ed9fd51a0f1d2a9949890
      //CoveredLines: [32, 61, 63, 65, 66, 67, 77, 78, 80, 81, 83, 84, 87, 90, 92, 100, 101, 102]
      //Input_0_String: \"(?:[^\"\\]|\\.)*\"
      //Assert: assertEquals(5, method_result.size());
      
      Tokenizer tokenizer0 = new Tokenizer();
      
      //Call method: tokenize
      TokenList tokenList0 = Tokenizer.tokenize("\"(?:[^\"\\]|\\.)*\"");
      
      //Test Result Assert
      assertEquals(5, tokenList0.size());
  }

  @Test(timeout = 4000)
  public void test_tokenize_11()  throws Throwable  {
      //caseID:140b5b030380c682892d33135d1b9f6e
      //CoveredLines: [32, 61, 63, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 90, 92, 100, 101, 102]
      //Input_0_String: 1.0
      //Assert: assertEquals(1, method_result.size());
      
      Tokenizer.QuotedString tokenizer_QuotedString0 = new Tokenizer.QuotedString("148");
      Tokenizer tokenizer0 = new Tokenizer();
      
      //Call method: tokenize
      TokenList tokenList0 = Tokenizer.tokenize("1.0");
      
      //Test Result Assert
      assertEquals(1, tokenList0.size());
  }

  @Test(timeout = 4000)
  public void test_tokenize_12()  throws Throwable  {
      //caseID:106e432bd960663934c37737ac89b04c
      //CoveredLines: [61, 63, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 77, 83, 84, 87, 90, 92]
      //Input_0_String: 1.3B0
      //Assert: assertEquals(2, method_result.size());
      
      
      //Call method: tokenize
      TokenList tokenList0 = Tokenizer.tokenize("1.3B0");
      
      //Test Result Assert
      assertEquals(2, tokenList0.size());
  }
}
